AL:
<AL>
    id:1AL
    anchor_x: 'center'
    anchor_y: 'top'
    Label:
        id:1ALS
        text:'SyllabusX'
        font_name: 'SylFont.ttf'
        size_hint: 0.3, 0.15
        font_size: self.size.texture_size[1]/2
        background_color: (0, 0.72, 0.68, 1)
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                pos: root.pos
                size: root.size