AL:


<AL@AnchorLayout>
    anchor_x: 'center'
    anchor_y: 'top'
    Label:
        text:'SyllabusX'
        font_name: 'SylFont.ttf'
        size_hint: 0.3, 0.15
        font_size: '50dp'
        background_color: (0, 0.72, 0.68, 1)
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                pos: self.pos
                size: self.size